# Generated by Django 3.2.9 on 2021-11-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('plant_type', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_date', models.DateTimeField(verbose_name='date watered')),
                ('water_id', models.IntegerField()),
                ('watered_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watering.plants')),
            ],
        ),
    ]
