# Generated by Django 3.2.9 on 2021-11-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watering', '0002_alter_watering_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watering',
            name='water_date',
            field=models.DateField(verbose_name='date watered'),
        ),
    ]
