# Generated by Django 3.2.9 on 2021-11-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watering', '0003_alter_watering_water_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='plant_type',
        ),
    ]
