# Generated by Django 3.2.9 on 2021-11-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watering', '0004_remove_plant_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='added_date',
            field=models.DateField(verbose_name='date added'),
        ),
    ]
